server:
   port: 10080
lance:
   mail:
      sender: pd_test@163.com
spring:
   datasource:
      username: dev
      password: dev
      url: jdbc:mysql://192.168.43.1:3306/dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
      #url: jdbc:mysql://192.168.0.110:3306/dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
      #url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
      driver-class-name: com.mysql.jdbc.Driver
   profiles:
      active: dev   
   freemarker:
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      enabled: true
      suffix: .ftl
      template-loader-path: classpath:/templates/
   mail:
      from: pd_test@163.com
      host: smtp.163.com
      username: pd_test@163.com
      password: JLQPFNTZVFXWUMJJ
      default-encoding: UTF-8
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
                  required: true
mybatis-plus:
   global-config:
      db-config:
         logic-delete-field: deleteFlag
         logic-delete-value: 1
         logic-not-delete-value: 0
   mapper-locations: classpath*:mapper/*.xml
   type-aliases-package: com.pd.businessobject
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl