server:
   port: 8081
lance:
   mail:
      sender: pd_test@163.com
spring:
   cache:
      type: REDIS
   redis:
      database: 0
      host: localhost
      password: ww
      port: 6379
      pool:
         max-idle: 8
         min-idle: 0
         max-active: 100
         max-wait: -1
   datasource:
      username: dev
      password: dev
      #username: postgres
      #password: testdev
      #url: jdbc:mysql://192.168.43.1:3306/dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
      url: jdbc:mysql://192.168.1.150:3306/dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
      #url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
      #url: jdbc:postgresql://localhost:5432/postgres
      driver-class-name: com.mysql.jdbc.Driver
      #driver-class-name: org.postgresql.Driver
   profiles:
      active: dev   
   freemarker:
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      enabled: true
      suffix: .ftl
      template-loader-path: classpath:/templates/
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
   mail:
      from: pd_test@163.com
      host: smtp.163.com
      username: pd_test@163.com
      password: JLQPFNTZVFXWUMJJ
      default-encoding: UTF-8
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
                  required: true
mybatis:
   configuration:
      map-underscore-to-camel-case: true
mybatis-plus:
   global-config:
      db-config:
         logic-delete-field: deleteFlag
         logic-delete-value: 1
         logic-not-delete-value: 0
   mapper-locations: classpath*:*mapper/*.xml
   type-aliases-package: com.pd.businessobject
   configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl